name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  verify:
    name: check pull request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: test & build
        run: |
          yarn install
          yarn test
          yarn build
