name: CI

on: 
  pull_request:
    branches: 
      - master

jobs:    
  verify:
    name: execute unit tests & build library
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        yarn install
        yarn test
        yarn build
